### ISSUE TITLE
[1.19.3] Client crash on looking up Antibarrel or hovering over it with REI -java.lang.RuntimeException: Tried to get data on the client?

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/NABBA#1]
https://gist.github.com/Reveter/408a4faa330aa6b27fc42789a0da31de#file-crash-2023-02-27_09-31-46-client-txt

reproduced here -
https://gist.github.com/Reveter/408a4faa330aa6b27fc42789a0da31de#file-crash-2023-02-27_09-34-37-client-txt

**Comment by Tfarcenim** [comment]
Fixed in 1.1.2
