### ISSUE TITLE
Dupe with Anti-Barrel

### ISSUE THREAD

**Issue by Reveter** [Tfarcenim/NABBA#3]
Anti-barrel placed inside of a barrel interface that is connected to an AE2 system via a storage bus, duplicates items by replacing an already existing item stack.
![anti-barrel](https://user-images.githubusercontent.com/8112174/222318521-86630558-0599-40d8-8825-9a3ac92a044c.gif)

**Comment by Tfarcenim** [comment]
Fixed in 1.1.4
